e:/crucial_venv/Scripts/python.exe -m pip install ipykernel -U --force-reinstall

In [4]:
! pip install numpy
! pip install pandas
! pip install pandasql

Requirement already satisfied: numpy in e:\crucial_venv\lib\site-packages (2.0.0)
Requirement already satisfied: pandas in e:\crucial_venv\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in e:\crucial_venv\lib\site-packages (from pandas) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\crucial_venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in e:\crucial_venv\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in e:\crucial_venv\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in e:\crucial_venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: numpy in e:\crucial_venv\lib\site-packages (from pandasql) (2.0.0)
Requirement already satisfied: pandas in e:\crucial_venv\lib\site-packages (from pandasql) (2.2.2)
Collecting sqlalchemy (from pandasql)
  Downloading SQLAlchemy-2.0.31-cp312-cp312-win_amd64.whl.metadata (9.9 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\crucial_venv\lib\site-packages (from pandas->pandasql) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in e:\crucial_venv\lib\site-packages (from pandas->pandasql) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in e:\crucial_venv\lib\site-packages (from pandas->pandasql) (2024.1)
Collecting typing-extensions>=4.6.0 (from sqlalchemy->pandasql)
  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting greenlet!=0.4.17 (from sqlalchemy->pandasql)
  Downloading greenlet-3.0.3-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: six>=1.5 in e:\crucial_venv\lib\site-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.16.0)
Downloading SQLAlchemy-2.0.31-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   - -------------------------------------- 0.1/2.1 MB 1.7 MB/s eta 0:00:02
   ---- ----------------------------------- 0.2/2.1 MB 2.3 MB/s eta 0:00:01
   ------- -------------------------------- 0.4/2.1 MB 2.3 MB/s eta 0:00:01
   ---------- ----------------------------- 0.6/2.1 MB 2.7 MB/s eta 0:00:01
   ------------- -------------------------- 0.7/2.1 MB 2.9 MB/s eta 0:00:01
   ---------------- ----------------------- 0.8/2.1 MB 3.0 MB/s eta 0:00:01
   ------------------ --------------------- 1.0/2.1 MB 2.9 MB/s eta 0:00:01
   ------------------------ --------------- 1.2/2.1 MB 3.3 MB/s eta 0:00:01
   ---------------------------- ----------- 1.5/2.1 MB 3.5 MB/s eta 0:00:01
   --------------------------------- ------ 1.8/2.1 MB 3.7 MB/s eta 0:00:01
   -------------------------------------- - 2.0/2.1 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 3.8 MB/s eta 0:00:00
Downloading greenlet-3.0.3-cp312-cp312-win_amd64.whl (293 kB)
   ---------------------------------------- 0.0/293.6 kB ? eta -:--:--
   ------------------------------------ --- 266.2/293.6 kB 8.3 MB/s eta 0:00:01
   ---------------------------------------- 293.6/293.6 kB 4.6 MB/s eta 0:00:00
Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (pyproject.toml): started
  Building wheel for pandasql (pyproject.toml): finished with status 'done'
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26799 sha256=7454edd5d28b764bba23ab4638d6638dc10461c77883d48009e81e92279c67bf
  Stored in directory: c:\users\anand\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local\pip\cache\wheels\15\a1\e7\6f92f295b5272ae5c02365e6b8fa19cb93f16a537090a1cf27
Successfully built pandasql
Installing collected packages: typing-extensions, greenlet, sqlalchemy, pandasql
Successfully installed greenlet-3.0.3 pandasql-0.7.3 sqlalchemy-2.0.31 typing-extensions-4.12.2

In [5]:
import numpy as np
import pandas as pd
from pandasql import sqldf
import datetime as dt

## Basic

In [40]:

# Create the DataFrame
data = {
    'ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 12, 22, 23, 24, 25],
    'Date': [
        '2022-01-05', '2022-01-10', '2022-01-15', '2022-01-20', '2022-01-25',
        '2022-02-01', '2022-02-05', '2022-02-10', '2022-02-15', '2022-02-20',
        '2022-02-25', '2022-03-01', '2022-03-05', '2022-03-10', '2022-03-15',
        '2022-03-20', '2022-03-25', '2022-04-01', '2022-04-05', '2022-04-10',
        '2022-04-15', '2022-04-20', '2022-04-25', '2022-05-01', '2022-05-05'
    ],
    'Customer_Name': [
        'John Smith', 'Mary Johnson', 'David Lee', 'Lisa Brown', 'Michael Wang',
    'Emily Chen', 'Brian Kim', 'Sarah Adams', 'Kevin Liu', 'Jessica Wu',
    'Alex Rodriguez', 'Olivia White', 'Daniel Park', 'Sophia Lee', 'Ethan Brown',
    'John Smith', 'Mary Johnson', 'David Lee', 'Lisa Brown', 'Michael Wang',
    'Emily Chen', 'Brian Kim', 'Sarah Adams', 'Kevin Liu', 'Jessica Wu'
        
    ],
    'Product_Category': [
        'Electronics', 'Apparel', 'Home & Garden', 'Electronics', 'Beauty',
        'Apparel', 'Electronics', 'Home & Garden', 'Beauty', 'Apparel',
        'Electronics', 'Home & Garden', 'Beauty', 'Apparel', 'Electronics',
        'Beauty', 'Apparel', 'Electronics', 'Home & Garden', 'Beauty',
        'Apparel', 'Electronics', 'Home & Garden', 'Beauty', 'Apparel'
    ],
    'Quantity': [3, 2, 5, 1, 4, 2, 3, 4, 1, 2, 5, 3, 2, 1, 4, 3, 1, 4, 2, 5, 3, 1, 4, 2, 5],
    'Price': [250, 80, 120, 350, 45, 75, 240, 110, 50, 70, 300, 130, 55, 60, 280, 60, 85, 220, 140, 55, 90, 260, 150, 65, 80]
}

df = pd.DataFrame(data)

# Display the DataFrame
df

    ID        Date   Customer_Name Product_Category  Quantity  Price
0    1  2022-01-05      John Smith      Electronics         3    250
1    2  2022-01-10    Mary Johnson          Apparel         2     80
2    3  2022-01-15       David Lee    Home & Garden         5    120
3    4  2022-01-20      Lisa Brown      Electronics         1    350
4    5  2022-01-25    Michael Wang           Beauty         4     45
5    6  2022-02-01      Emily Chen          Apparel         2     75
6    7  2022-02-05       Brian Kim      Electronics         3    240
7    8  2022-02-10     Sarah Adams    Home & Garden         4    110
8    9  2022-02-15       Kevin Liu           Beauty         1     50
9   10  2022-02-20      Jessica Wu          Apparel         2     70
10  11  2022-02-25  Alex Rodriguez      Electronics         5    300
11  12  2022-03-01    Olivia White    Home & Garden         3    130
12  13  2022-03-05     Daniel Park           Beauty         2     55
13  14  2022-03-10      Sophia Lee          Apparel         1     60
14  15  2022-03-15     Ethan Brown      Electronics         4    280
15  16  2022-03-20      John Smith           Beauty         3     60
16  17  2022-03-25    Mary Johnson          Apparel         1     85
17  18  2022-04-01       David Lee      Electronics         4    220
18  19  2022-04-05      Lisa Brown    Home & Garden         2    140
19  20  2022-04-10    Michael Wang           Beauty         5     55
20  12  2022-04-15      Emily Chen          Apparel         3     90
21  22  2022-04-20       Brian Kim      Electronics         1    260
22  23  2022-04-25     Sarah Adams    Home & Garden         4    150
23  24  2022-05-01       Kevin Liu           Beauty         2     65
24  25  2022-05-05      Jessica Wu          Apparel         5     80

In [56]:
# Q1  : For each product category find the "Total price", "Total quantity", "Average price per unit"

# Q1e : for transactions happenned between "2022-02-01" and "2022-04-25" 
# Q1e : and get the Product_Category with sales less than 1000

# Q2 Rank them in the order of their tot_sales

    ID        Date   Customer_Name Product_Category  Quantity  Price
0    1  2022-01-05      John Smith      Electronics         3    250
1    2  2022-01-10    Mary Johnson          Apparel         2     80
2    3  2022-01-15       David Lee    Home & Garden         5    120
3    4  2022-01-20      Lisa Brown      Electronics         1    350
4    5  2022-01-25    Michael Wang           Beauty         4     45
5    6  2022-02-01      Emily Chen          Apparel         2     75
6    7  2022-02-05       Brian Kim      Electronics         3    240
7    8  2022-02-10     Sarah Adams    Home & Garden         4    110
8    9  2022-02-15       Kevin Liu           Beauty         1     50
9   10  2022-02-20      Jessica Wu          Apparel         2     70
10  11  2022-02-25  Alex Rodriguez      Electronics         5    300
11  12  2022-03-01    Olivia White    Home & Garden         3    130
12  13  2022-03-05     Daniel Park           Beauty         2     55
13  14  2022-03-10      Sophia Lee          Apparel         1     60
14  15  2022-03-15     Ethan Brown      Electronics         4    280
15  16  2022-03-20      John Smith           Beauty         3     60
16  17  2022-03-25    Mary Johnson          Apparel         1     85
17  18  2022-04-01       David Lee      Electronics         4    220
18  19  2022-04-05      Lisa Brown    Home & Garden         2    140
19  20  2022-04-10    Michael Wang           Beauty         5     55
20  12  2022-04-15      Emily Chen          Apparel         3     90
21  22  2022-04-20       Brian Kim      Electronics         1    260
22  23  2022-04-25     Sarah Adams    Home & Garden         4    150
23  24  2022-05-01       Kevin Liu           Beauty         2     65
24  25  2022-05-05      Jessica Wu          Apparel         5     80

In [57]:
# Q1 Answer : 
dfs_q1 = sqldf("""
              
select *
from df

""")
dfs_q1

  Product_Category  tot_qty  tot_price         ppq
0          Apparel       16        540   43.285714
1           Beauty       17        330   25.166667
2      Electronics       21       1900  136.857143
3    Home & Garden       18        650   40.200000

In [59]:
# Q1e Answer : 
dfs_q1e = sqldf("""
              
select *
from df

""")
df_q1e

  Product_Category  tot_qty  tot_price
0          Apparel        9        380
1           Beauty       11        220
2    Home & Garden       13        530

In [60]:
# Q2 Answer : 
dfs_q2 = sqldf("""      
              
select *
from df

""")
dfs_q2

  Product_Category  tot_qty  tot_price  sales_rnk
0    Home & Garden       13        530          1
1          Apparel        9        380          2
2           Beauty       11        220          3